{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNReu5rxa0ujMKIXdkPUBZt",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bhanu859/python-/blob/main/fake%20job%20posting.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "CXc697pkr0Au",
        "outputId": "e4daff89-8dc9-449f-f97a-73c2d94fc932"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--- 1. Creating Synthetic Dataset ---\n",
            "Dataframe created with 60 entries.\n",
            "                                               title  fraudulent\n",
            "0                      Software Engineer - Python/AI           0\n",
            "1  WORK FROM HOME - URGENT HIRE! No Experience Ne...           1\n",
            "2                          Data Scientist, NLP Focus           0\n",
            "3        Part-Time Remote Assistant - Easy Money Now           1\n",
            "4                  Senior Frontend Developer (React)           0\n",
            "\n",
            "--- 2. Data Cleaning and Preprocessing ---\n",
            "--- 3. Feature Extraction (TF-IDF) ---\n",
            "TF-IDF features created. Training set shape: (42, 1033)\n",
            "\n",
            "--- 4. Training Logistic Regression Model ---\n",
            "\n",
            "--- 5. Prediction and Evaluation ---\n",
            "**Model Accuracy: 0.8889**\n",
            "\n",
            "Classification Report:\n",
            "              precision    recall  f1-score   support\n",
            "\n",
            "    Real (0)       0.83      1.00      0.91        10\n",
            "    Fake (1)       1.00      0.75      0.86         8\n",
            "\n",
            "    accuracy                           0.89        18\n",
            "   macro avg       0.92      0.88      0.88        18\n",
            "weighted avg       0.91      0.89      0.89        18\n",
            "\n",
            "\n",
            "--- 6. Example Prediction ---\n",
            "\n",
            "Example Posting 1: 'Fantastic opportunity! Earn over $10k a month with zero work. Apply now by sending your SSN and $500 fee.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 2: 'Hiring for Senior Java Developer with 5+ years experience in Spring Boot and microservices architecture.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 3: 'Become a millionaire overnight! Invest small amount, get huge returns. Limited time offer.'\n",
            "-> Predicted Class: FAKE (1)\n",
            "\n",
            "Example Posting 4: 'Data Engineer - Apache Spark, SQL, Cloud Platforms.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 5: 'Remote Customer Service - Flexible Hours. Must have reliable internet and good communication.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 6: 'Need help processing payments, fast cash, no questions asked. Large payout.'\n",
            "-> Predicted Class: FAKE (1)\n",
            "\n",
            "Example Posting 7: 'Urgent! Crypto investor seeks partner to transfer funds. Guaranteed profit.'\n",
            "-> Predicted Class: FAKE (1)\n",
            "\n",
            "Example Posting 8: 'Marketing Coordinator - Social Media and Content Creation.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 9: 'Entry Level Software Tester - Manual and Automated Testing.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 10: 'Earn $3000 daily from home! Only requires a small upfront fee for materials.'\n",
            "-> Predicted Class: FAKE (1)\n",
            "\n",
            "Example Posting 11: 'Lead UX Designer - Figma, User Research, Prototyping.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 12: 'Get rich working from home, no experience needed! Just send your bank account details.'\n",
            "-> Predicted Class: FAKE (1)\n",
            "\n",
            "Example Posting 13: 'Junior Python Developer - Django/Flask experience.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 14: 'Work from home typing jobs. Send personal details and application fee to start.'\n",
            "-> Predicted Class: FAKE (1)\n",
            "\n",
            "Example Posting 15: 'Senior Product Manager - AI/ML Focus.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 16: 'Investment opportunity: double your money in 24 hours! Small initial capital required.'\n",
            "-> Predicted Class: FAKE (1)\n",
            "\n",
            "Example Posting 17: 'Operations Manager - Logistics and Supply Chain.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 18: 'Customer Service Representative - Call Center.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 19: 'Financial Analyst - Equity Research.'\n",
            "-> Predicted Class: REAL (0)\n",
            "\n",
            "Example Posting 20: 'Earn $5000 a week! Click this link to provide your info and get started now.'\n",
            "-> Predicted Class: FAKE (1)\n"
          ]
        }
      ],
      "source": [
        "import pandas as pd\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.feature_extraction.text import TfidfVectorizer\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.metrics import classification_report, accuracy_score\n",
        "import re\n",
        "import nltk\n",
        "from nltk.corpus import stopwords\n",
        "\n",
        "# Ensure NLTK resources are downloaded (run once)\n",
        "try:\n",
        "    stopwords.words('english')\n",
        "except LookupError:\n",
        "    nltk.download('stopwords')\n",
        "\n",
        "# --- 1. CREATE SYNTHETIC DATASET (CSV-like structure in program) ---\n",
        "print(\"--- 1. Creating Synthetic Dataset ---\")\n",
        "\n",
        "data = {\n",
        "    'job_id': list(range(1, 61)),\n",
        "    'title': [\n",
        "        \"Software Engineer - Python/AI\",\n",
        "        \"WORK FROM HOME - URGENT HIRE! No Experience Needed $$$\",\n",
        "        \"Data Scientist, NLP Focus\",\n",
        "        \"Part-Time Remote Assistant - Easy Money Now\",\n",
        "        \"Senior Frontend Developer (React)\",\n",
        "        \"HIRING NOW! Get Rich Quick - Must Apply Today\",\n",
        "        \"Marketing Manager - Digital Strategy\",\n",
        "        \"Entry Level Customer Support Rep\",\n",
        "        \"Executive Personal Assistant - High Salary Confidential\",\n",
        "        \"Cloud Architect Specialist\",\n",
        "        \"Junior Frontend Developer - HTML/CSS/JS\",\n",
        "        \"Make $5000 a week from home - No skills required!\",\n",
        "        \"Machine Learning Engineer - Deep Learning\",\n",
        "        \"Urgent! Need help moving money. Big commission. Contact now!\",\n",
        "        \"DevOps Engineer - AWS/Kubernetes\",\n",
        "        \"Work from anywhere! Earn passive income instantly. Free training.\",\n",
        "        \"Product Manager - SaaS Experience\",\n",
        "        \"Customer Success Manager - Tech Industry\",\n",
        "        \"Investment Opportunity - Guaranteed 200% return in 2 days!\",\n",
        "        \"Graphic Designer - Adobe Creative Suite\",\n",
        "        \"Full Stack Developer - Node.js/Angular\",\n",
        "        \"Earn passive income at home! No skills, just pay a small fee.\",\n",
        "        \"Senior Data Analyst - SQL/Tableau\",\n",
        "        \"Be your own boss! Work 2 hours a day for high returns. Start now with a deposit.\",\n",
        "        \"Business Development Manager - SaaS Sales\",\n",
        "        \"Get instant cash! Transfer funds for a huge commission. Act fast!\",\n",
        "        \"UI/UX Designer - Adobe XD/Figma\",\n",
        "        \"Customer Support Specialist - Remote\",\n",
        "        \"Personal Assistant - VIP Clients. Confidentiality required, upfront payment for background check.\",\n",
        "        \"Network Engineer - Cisco/Juniper\",\n",
        "        \"Junior Marketing Specialist - Social Media\",\n",
        "        \"Make money online easily! Just provide your bank details for direct deposit.\",\n",
        "        \"Cybersecurity Analyst - SIEM/Endpoint Protection\",\n",
        "        \"Financial Advisor - High Net Worth Clients. Guaranteed returns with initial fee.\",\n",
        "        \"Mobile App Developer - iOS/Android\",\n",
        "        \"Financial freedom today! Buy our exclusive guide for just $99.\",\n",
        "        \"Content Writer - Tech Blog\",\n",
        "        \"Sales Representative - Enterprise Software\",\n",
        "        \"Event Manager - Corporate Events\",\n",
        "        \"Work from home assembling products. Send us money for supplies.\",\n",
        "        # Additional Real Job Postings\n",
        "        \"Marketing Specialist - SEO/SEM\",\n",
        "        \"Customer Support Representative - SaaS\",\n",
        "        \"Data Analyst - BI Tools\",\n",
        "        \"HR Manager - Talent Acquisition\",\n",
        "        \"Operations Coordinator\",\n",
        "        \"Project Manager - Software Development\",\n",
        "        \"Financial Controller\",\n",
        "        \"Research Scientist - Chemistry\",\n",
        "        \"Legal Counsel - Corporate\",\n",
        "        \"IT Support Technician - Help Desk\",\n",
        "        # Additional Fake Job Postings\n",
        "        \"Earn Easy Money from Home - Simple Tasks, Immediate Payout!\",\n",
        "        \"Investment Scheme - Guaranteed High Returns, Limited Spots!\",\n",
        "        \"Personal Assistant - Confidential Tasks, Upfront Fee Required\",\n",
        "        \"Work from Home - Data Entry, No Experience, Pay for Training Kit\",\n",
        "        \"Crypto Trading - Make Millions Overnight, Small Capital Needed\",\n",
        "        \"Unclaimed Funds Assistant - Huge Commission for Transfer Help\",\n",
        "        \"Secret Shopper - Get Paid to Shop, Send Money for Instructions\",\n",
        "        \"Government Grant - Apply Now, Processing Fee Required\",\n",
        "        \"Online Survey Taker - High Pay, Just Provide Bank Details\",\n",
        "        \"Event Planner - Remote, Send Payment for Supplies & Materials\"\n",
        "    ],\n",
        "    'description': [\n",
        "        \"Develop and deploy scalable backend services using Python and Flask. Experience with ML frameworks like PyTorch is a plus.\",\n",
        "        \"Stop searching! We offer an unbelievable opportunity to make thousands daily. Send us your bank info to start. Limited spots available.\",\n",
        "        \"Research and develop advanced NLP models to improve our proprietary search engine.\",\n",
        "        \"Simple tasks like data entry and basic communication. Pay is $50/hour. We need you to pay a small processing fee first.\",\n",
        "        \"Build and maintain user-facing features using React.js and Redux. Collaborate with UX/UI team.\",\n",
        "        \"Invest in our 'exclusive' cryptocurrency. You'll work 2 hours a day and earn a 6-figure salary. No resume needed.\",\n",
        "        \"Plan and execute all digital marketing, including SEO/SEM, email, and social media.\",\n",
        "        \"Handle inbound customer inquiries via chat and email. Opportunity for growth.\",\n",
        "        \"Manage CEO's personal schedule and travel. Require a background check and a one-time 'security deposit' before interview.\",\n",
        "        \"Design and implement secure, high-availability cloud solutions on AWS/Azure.\",\n",
        "        \"Develop responsive user interfaces using HTML, CSS, and JavaScript. Collaborate with design team.\",\n",
        "        \"Revolutionary system lets you earn without effort! Just provide your personal details and credit card info.\",\n",
        "        \"Design, develop, and deploy machine learning models using TensorFlow/PyTorch for various applications.\",\n",
        "        \"A wealthy individual needs assistance with financial transfers. High compensation for quick action. Send your bank details.\",\n",
        "        \"Implement and manage CI/CD pipelines, automate infrastructure on AWS, and manage Kubernetes clusters.\",\n",
        "        \"Discover the secret to financial freedom! No experience required, just pay a small membership fee.\",\n",
        "        \"Define product vision, strategy, and roadmap for our SaaS products. Work closely with engineering and sales.\",\n",
        "        \"Build strong relationships with clients, ensure customer satisfaction, and drive product adoption for enterprise clients.\",\n",
        "        \"Limited-time offer! Double your money in 48 hours. Requires an initial 'investment' fee. Don't miss out!\",\n",
        "        \"Create compelling visual designs for marketing materials, websites, and user interfaces using Photoshop, Illustrator, and InDesign.\",\n",
        "        \"Develop and maintain full-stack web applications using Node.js, Express, and Angular. Collaborate with product teams.\",\n",
        "        \"Quit your job! Financial independence is just a click away. Pay a small processing fee for immediate access.\",\n",
        "        \"Analyze complex datasets, create dashboards, and generate reports using SQL and Tableau. Present findings to stakeholders.\",\n",
        "        \"Work 1 hour a day, earn 7 figures! Guaranteed income with our secret system. Investment required.\",\n",
        "        \"Drive revenue growth by identifying new business opportunities and managing the sales cycle for SaaS products.\",\n",
        "        \"International client needs urgent assistance with money transfers. High commission for quick and discreet action. Send bank details.\",\n",
        "        \"Design intuitive and engaging user interfaces and experiences for web and mobile applications using Adobe XD and Figma.\",\n",
        "        \"Provide technical support and assistance to customers via phone, email, and chat. Strong problem-solving skills.\",\n",
        "        \"Support high-profile executive. Duties include scheduling, travel, and confidential matters. A substantial security deposit is required for vetting.\",\n",
        "        \"Configure, implement, and troubleshoot network infrastructure devices such as routers, switches, and firewalls.\",\n",
        "        \"Assist in executing marketing campaigns across various social media platforms. Content creation and analytics.\",\n",
        "        \"We need your help with a financial transaction. Simply provide your account info to receive a large sum. No questions asked.\",\n",
        "        \"Monitor security systems, analyze threats, and respond to incidents. Experience with SIEM tools and endpoint protection.\",\n",
        "        \"Unlock massive wealth! Invest with us and get a guaranteed 500% return in days. Just a small initial capital needed.\",\n",
        "        \"Develop and maintain mobile applications for iOS and Android platforms using Swift/Kotlin or React Native.\",\n",
        "        \"Discover the secret to making millions from your couch! Purchase our exclusive e-book for life-changing income.\",\n",
        "        \"Write engaging and informative content for a technology blog, including articles, whitepapers, and case studies.\",\n",
        "        \"Identify and close new business opportunities within the enterprise sector. Strong negotiation and communication skills.\",\n",
        "        \"Plan, organize, and execute corporate events, conferences and seminars. Manage budgets and logistics.\",\n",
        "        \"Assemblers needed! Work from home on flexible hours. You just need to purchase our specialized kit for training and materials.\",\n",
        "        # Additional Real Job Postings Descriptions\n",
        "        \"Develop and execute SEO/SEM strategies, manage social media campaigns, and analyze marketing performance.\",\n",
        "        \"Provide excellent customer service to SaaS clients, resolve issues, and ensure product satisfaction.\",\n",
        "        \"Analyze complex datasets using BI tools like Tableau and Power BI, create reports, and derive actionable insights.\",\n",
        "        \"Manage the full recruitment lifecycle, from sourcing to onboarding, and develop HR policies and programs.\",\n",
        "        \"Coordinate daily operations, manage logistics, and support various departments to ensure efficiency.\",\n",
        "        \"Lead software development projects from conception to deployment, ensuring timely delivery and quality.\",\n",
        "        \"Oversee financial operations, prepare financial statements, manage budgets, and ensure compliance.\",\n",
        "        \"Conduct scientific research in chemistry, develop new compounds, and publish findings.\",\n",
        "        \"Provide legal advice on corporate matters, draft contracts, and ensure regulatory compliance.\",\n",
        "        \"Provide technical support to end-users, troubleshoot hardware and software issues, and manage IT assets.\",\n",
        "        # Additional Fake Job Postings Descriptions\n",
        "        \"Perform simple online tasks for high pay, no experience needed. Immediate payment after a small registration fee.\",\n",
        "        \"Join our exclusive investment group! Guaranteed returns of 500% in a week with a minimal upfront deposit. Limited membership.\",\n",
        "        \"Assist a busy executive with confidential errands and personal tasks. A 'security clearance' fee is required for background checks.\",\n",
        "        \"Type documents from home, set your own hours. Purchase our mandatory training software and supplies kit to begin.\",\n",
        "        \"Become a crypto millionaire overnight! Our AI-powered system guarantees massive profits with a small initial investment.\",\n",
        "        \"Help transfer large sums of unclaimed inheritance money. Receive a huge percentage for your assistance. Bank details required.\",\n",
        "        \"Get paid to shop at luxury stores! Become a secret shopper by sending a small fee for your first assignment kit.\",\n",
        "        \"Apply for a government grant you qualify for! A processing fee is required to secure your application and funds.\",\n",
        "        \"Complete quick online surveys for high payouts. Just provide your bank account information for direct deposits.\",\n",
        "        \"Organize events from your home. We provide clients, you just need to cover the initial cost of event planning materials.\"\n",
        "    ],\n",
        "    # 0 = Real, 1 = Fake\n",
        "    'fraudulent': [\n",
        "        0, 1, 0, 1, 0, 1, 0, 0, 1, 0,\n",
        "        0, 1, 0, 1, 0, 1, 0, 0, 1, 0,\n",
        "        0, 1, 0, 1, 0, 1, 0, 0, 1, 0,\n",
        "        0, 1, 0, 1, 0, 1, 0, 0, 0, 1,\n",
        "        # Labels for Additional Real Job Postings\n",
        "        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
        "        # Labels for Additional Fake Job Postings\n",
        "        1, 1, 1, 1, 1, 1, 1, 1, 1, 1\n",
        "    ]\n",
        "}\n",
        "\n",
        "df = pd.DataFrame(data)\n",
        "print(f\"Dataframe created with {len(df)} entries.\")\n",
        "print(df[['title', 'fraudulent']].head())\n",
        "\n",
        "# --- 2. DATA CLEANING AND PREPROCESSING ---\n",
        "print(\"\\n--- 2. Data Cleaning and Preprocessing ---\")\n",
        "stop_words = set(stopwords.words('english'))\n",
        "\n",
        "def clean_text(text):\n",
        "    # Convert to lowercase\n",
        "    text = str(text).lower()\n",
        "    # Remove special characters, numbers, and punctuation\n",
        "    text = re.sub(r'[^a-zA-Z\\s]', '', text)\n",
        "    # Tokenize and remove stop words\n",
        "    tokens = text.split()\n",
        "    tokens = [word for word in tokens if word not in stop_words]\n",
        "    return ' '.join(tokens)\n",
        "\n",
        "# Combine 'title' and 'description' for better features\n",
        "df['text'] = df['title'] + ' ' + df['description']\n",
        "# Apply the cleaning function\n",
        "df['cleaned_text'] = df['text'].apply(clean_text)\n",
        "\n",
        "#\n",
        "\n",
        "# --- 3. FEATURE EXTRACTION (TF-IDF) ---\n",
        "print(\"--- 3. Feature Extraction (TF-IDF) ---\")\n",
        "X = df['cleaned_text']\n",
        "y = df['fraudulent']\n",
        "\n",
        "# Split data\n",
        "X_train, X_test, y_train, y_test = train_test_split(\n",
        "    X, y, test_size=0.3, random_state=42, stratify=y\n",
        ")\n",
        "\n",
        "# Initialize TF-IDF Vectorizer\n",
        "# max_features is crucial for large, real datasets\n",
        "tfidf_vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))\n",
        "\n",
        "# Fit on training data and transform both sets\n",
        "X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)\n",
        "X_test_tfidf = tfidf_vectorizer.transform(X_test)\n",
        "\n",
        "print(f\"TF-IDF features created. Training set shape: {X_train_tfidf.shape}\")\n",
        "\n",
        "# --- 4. MACHINE LEARNING MODEL (LOGISTIC REGRESSION) ---\n",
        "print(\"\\n--- 4. Training Logistic Regression Model ---\")\n",
        "\n",
        "# Initialize and train the model\n",
        "model = LogisticRegression(random_state=42, solver='liblinear')\n",
        "model.fit(X_train_tfidf, y_train)\n",
        "\n",
        "# --- 5. PREDICTION AND EVALUATION ---\n",
        "print(\"\\n--- 5. Prediction and Evaluation ---\")\n",
        "\n",
        "# Make predictions on the test set\n",
        "y_pred = model.predict(X_test_tfidf)\n",
        "accuracy = accuracy_score(y_test, y_pred)\n",
        "\n",
        "print(f\"**Model Accuracy: {accuracy:.4f}**\")\n",
        "print(\"\\nClassification Report:\")\n",
        "print(classification_report(y_test, y_pred, target_names=['Real (0)', 'Fake (1)']))\n",
        "\n",
        "# --- 6. EXAMPLE PREDICTION ---\n",
        "print(\"\\n--- 6. Example Prediction ---\")\n",
        "\n",
        "new_job_posting = [\n",
        "    \"Fantastic opportunity! Earn over $10k a month with zero work. Apply now by sending your SSN and $500 fee.\", # Should be FAKE (1)\n",
        "    \"Hiring for Senior Java Developer with 5+ years experience in Spring Boot and microservices architecture.\", # Should be REAL (0)\n",
        "    \"Become a millionaire overnight! Invest small amount, get huge returns. Limited time offer.\", # Should be FAKE (1)\n",
        "    \"Data Engineer - Apache Spark, SQL, Cloud Platforms.\", # Should be REAL (0)\n",
        "    \"Remote Customer Service - Flexible Hours. Must have reliable internet and good communication.\", # Should be REAL (0)\n",
        "    \"Need help processing payments, fast cash, no questions asked. Large payout.\", # Should be FAKE (1)\n",
        "    \"Urgent! Crypto investor seeks partner to transfer funds. Guaranteed profit.\", # Should be FAKE (1)\n",
        "    \"Marketing Coordinator - Social Media and Content Creation.\", # Should be REAL (0)\n",
        "    \"Entry Level Software Tester - Manual and Automated Testing.\", # Should be REAL (0)\n",
        "    \"Earn $3000 daily from home! Only requires a small upfront fee for materials.\", # Should be FAKE (1)\n",
        "    \"Lead UX Designer - Figma, User Research, Prototyping.\", # Should be REAL (0)\n",
        "    \"Get rich working from home, no experience needed! Just send your bank account details.\", # Should be FAKE (1)\n",
        "    \"Junior Python Developer - Django/Flask experience.\", # Should be REAL (0)\n",
        "    \"Work from home typing jobs. Send personal details and application fee to start.\", # Should be FAKE (1)\n",
        "    \"Senior Product Manager - AI/ML Focus.\", # Should be REAL (0)\n",
        "    \"Investment opportunity: double your money in 24 hours! Small initial capital required.\", # Should be FAKE (1)\n",
        "    \"Operations Manager - Logistics and Supply Chain.\", # Should be REAL (0)\n",
        "    \"Customer Service Representative - Call Center.\", # Should be REAL (0)\n",
        "    \"Financial Analyst - Equity Research.\", # Should be REAL (0)\n",
        "    \"Earn $5000 a week! Click this link to provide your info and get started now.\", # Should be FAKE (1)\n",
        "\n",
        "\n",
        "]\n",
        "\n",
        "# Clean the new data\n",
        "cleaned_new_data = [clean_text(post) for post in new_job_posting]\n",
        "\n",
        "# Vectorize the new data\n",
        "new_data_tfidf = tfidf_vectorizer.transform(cleaned_new_data)\n",
        "\n",
        "# Predict\n",
        "predictions = model.predict(new_data_tfidf)\n",
        "\n",
        "for i, post in enumerate(new_job_posting):\n",
        "    print(f\"\\nExample Posting {i+1}: '{post}'\")\n",
        "    print(f\"-> Predicted Class: {'FAKE' if predictions[i] == 1 else 'REAL'} ({predictions[i]})\")\n"
      ]
    }
  ]
}